CREATE TABLE CUSTOMERS(
   ID INT NOT NULL,
   NAME VARCHAR (20) NULL,
   AGE INT NULL,
   ADDRESS CHAR (25) ,
   SALARY DECIMAL (18, 2),       
   PRIMARY KEY (ID)
);

INSERT INTO CUSTOMERS (ID,NAME,AGE,ADDRESS,SALARY)
VALUES (1, 'Ramesh', 32, 'Ahmedabad', 2000.00 );

INSERT INTO CUSTOMERS (ID,NAME,AGE,ADDRESS,SALARY)
VALUES (2, 'Khilan', 25, 'Delhi', 1500.00 );

INSERT INTO CUSTOMERS (ID,NAME,AGE,ADDRESS,SALARY)
VALUES (3, 'kaushik', 23, 'Kota', 2000.00 );

INSERT INTO CUSTOMERS (ID,NAME,AGE,ADDRESS,SALARY)
VALUES (4, 'Chaitali', 25, 'Mumbai', 6500.00 );

INSERT INTO CUSTOMERS (ID,NAME,AGE,ADDRESS,SALARY)
VALUES (5, 'Hardik', 27, 'Bhopal', 8500.00 );

INSERT INTO CUSTOMERS (ID,NAME,AGE,ADDRESS,SALARY)
VALUES (6, 'Komal', 22, 'MP', 4500.00 );

SELECT * FROM CUSTOMERS;
SELECT name FROM CUSTOMERS;
SELECT NAME, AGE FROM CUSTOMERS;
SELECT * FROM CUSTOMERS LIMIT 2;
SELECT DISTINCT AGE FROM CUSTOMERS;
SELECT DISTINCT SALARY FROM CUSTOMERS;

SELECT CUSTOMERS.NAME FROM CUSTOMERS;
SELECT NAME AS NAMA_PANGGILAN FROM CUSTOMERS;
SELECT NAME AS NAMA_PANGGILAN, AGE AS UMUR FROM CUSTOMERS;
SELECT NAME NAMA_LENGKAP FROM CUSTOMERS;
SELECT CUSTOMERS.NAME AS NAMA_DEPAN FROM CUSTOMERS;
SELECT * FROM CUSTOMERS AS PELANGGAN;
SELECT NAME FROM CUSTOMERS AS PELANGGAN;
SELECT PELANGGAN.NAME FROM CUSTOMERS AS PELANGGAN;
SELECT PELANGGAN.NAME AS NAMA FROM CUSTOMERS AS PELANGGAN;

---FILTERING----
SELECT * FROM CUSTOMERS WHERE NAME = 'Ramesh';
SELECT * FROM CUSTOMERS WHERE NAME = 'Ramesh' or NAME = 'Khilan';
SELECT * FROM CUSTOMERS WHERE AGE > 23;
SELECT * FROM CUSTOMERS WHERE NAME = 'Ramesh' OR AGE < 23;
SELECT * FROM CUSTOMERS WHERE NAME IN ('Ramesh', 'Khilan');
SELECT * FROM CUSTOMERS WHERE NAME NOT IN ('Ramesh', 'Khilan');
SELECT * from CUSTOMERS WHERE NAME LIKE('%dik');
SELECT * from CUSTOMERS WHERE NAME LIKE('Ram%');
